name: Java CI with Gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Tests
      run: ./gradlew clean test "-Dselenide.headless=true"
    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      if: success() || failure() 
      with:
        name: allureReport
        path: build/allure-results
  report:
    runs-on: ubuntu-latest
    needs: tests 
    if: ${{ always() }} 
    steps:
    - name: Download Test Reports Folder
      uses: actions/download-artifact@v4
      with:
        name: allureReport 
